/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   cuba-entities.html
 */

/// <reference path="cuba-data-loading-behavior.d.ts" />
/// <reference path="../cuba-app/cuba-app-aware-behavior.d.ts" />

/**
 * The `cuba-entities` element provides an ability to load list of entities.
 */
interface CubaEntitiesElement extends Polymer.Element, CubaAppAwareBehavior, CubaDataLoadingBehavior {

  /**
   * Entity name as specified in domain model class via `@Entity` annotation e.g. sec$User
   */
  entityName: string|null|undefined;

  /**
   * Name of the view which is used for loading entities.
   */
  view: string|null|undefined;

  /**
   * Name of the field to be sorted by. If the name is preceeding by the '+' character,
   * then the sort order is ascending, if by the '-' character then descending.
   * If there is no special character before the property name, then ascending sort will be used.
   */
  sort: string|null|undefined;

  /**
   * Number of extracted entities.
   */
  limit: number|null|undefined;

  /**
   * Position of the first result to retrieve.
   */
  offset: number|null|undefined;
  provideCount: boolean|null|undefined;
  readonly count: number|null|undefined;
  _loadMoreOffset: number|null|undefined;

  /**
   * Deletes entity and removes it from `data` collection.
   */
  remove(entity: any): Promise<any>|null;
  loadMore(): any;
  loadCount(abortable: any): any;
  _getOptions(): any;
}

interface HTMLElementTagNameMap {
  "cuba-entities": CubaEntitiesElement;
}
