/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   cuba-query.html
 */

/// <reference path="cuba-data-loading-behavior.d.ts" />
/// <reference path="../cuba-app/cuba-app-aware-behavior.d.ts" />

/**
 * The `cuba-query` element provides an ability to load list of entities using predefined query.
 * See https://doc.cuba-platform.com/manual-latest/rest_api_v2_queries_config.html
 */
interface CubaQueryElement extends Polymer.Element, CubaAppAwareBehavior, CubaDataLoadingBehavior {

  /**
   * Entity name as specified in domain model class via `@Entity` annotation e.g. sec$User
   */
  entityName: string|null|undefined;
  queryName: string|null|undefined;

  /**
   * Query params
   */
  params: object|null|undefined;
  provideCount: boolean|null|undefined;
  readonly count: number|null|undefined;
  _loadMoreOffset: number|null|undefined;
  remove(entity: any): any;
  loadMore(): any;
  loadCount(abortable: any): any;
}

interface HTMLElementTagNameMap {
  "cuba-query": CubaQueryElement;
}
