/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   cuba-data.html
 */

/// <reference path="cuba-entities.d.ts" />
/// <reference path="cuba-entity.d.ts" />
/// <reference path="cuba-query.d.ts" />
/// <reference path="cuba-service.d.ts" />

